### ISSUE TITLE
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'

### ISSUE THREAD

**Issue by tmcothran** [ccnmtl/fdfgen#12]
When I try to check a box in a pdf, I get this error:

```
Traceback (most recent call last):
  File "./create_pdf.py", line 141, in <module>
    run_script()
  File "./create_pdf.py", line 129, in run_script
    template_type='pdf' 
  File "./create_pdf.py", line 77, in fillOutPdf
    fdf = forge_fdf("", fields, [], [], [])
  File "/home/tmcothran/Python_Projects/virtualenvs/Document_Generator/lib/python3.4/site-packages/fdfgen/__init__.py", line 101, in forge_fdf
    checkbox_checked_name)))
  File "/home/tmcothran/Python_Projects/virtualenvs/Document_Generator/lib/python3.4/site-packages/fdfgen/__init__.py", line 50, in handle_data_strings
    value = b'/%s' % checkbox_checked_name
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
```
I tried passing the argument `checked_box_name=b"On"`, and I got this error instead:
```
File "./create_pdf.py", line 141, in <module>
    run_script()
  File "./create_pdf.py", line 129, in run_script
    template_type='pdf'    
  File "./create_pdf.py", line 77, in fillOutPdf
    fdf = forge_fdf("", fields, [], [], [], checkbox_checked_name=b"On")
  File "/home/tmcothran/Python_Projects/virtualenvs/Document_Generator/lib/python3.4/site-packages/fdfgen/__init__.py", line 101, in forge_fdf
    checkbox_checked_name)))
  File "/home/tmcothran/Python_Projects/virtualenvs/Document_Generator/lib/python3.4/site-packages/fdfgen/__init__.py", line 50, in handle_data_strings
    value = b'/%s' % checkbox_checked_name
```
I'm very new to programming, and since there's no documentation on the checkboxes, I'm trying to do it from looking at the code and the comments in the code. So I might just be doing it wrong. I'm using Python 3.4.

**Comment by spaetz** [comment]
What happens if you simply use checked_box_name="On"?

**Comment by Jenselme** [comment]
Hi,

I just encountered the same problem. If I replace `checkbox_checked_name=b"Yes"` by `checkbox_checked_name="On"`, I get:

```
File "/home/jenselme/.virtualenvs/test/lib/python3.4/site-packages/fdfgen-0.12.1-py3.4.egg/fdfgen/__init__.py", line 101, in forge_fdf
    checkbox_checked_name)))
  File "/home/jenselme/.virtualenvs/test/lib/python3.4/site-packages/fdfgen-0.12.1-py3.4.egg/fdfgen/__init__.py", line 50, in handle_data_strings
    value = b'/%s' % checkbox_checked_name
TypeError: unsupported operand type(s) for %: 'bytes' and 'str'
```

I think it comes from the fact that the `%` operator is not supported for bytes in python 3. The `format` method is not supported either. I think the solution is to use a string instead of bytes for formatting.

**Comment by Jenselme** [comment]
Thanks for the quick merge! Can we have a new release with this merge?

**Comment by thraxil** [comment]
Yeah, it's coming. (We're actually in the midst of python 2 -> 3 porting right now as well)

**Comment by Jenselme** [comment]
Awsome, thanks!
